name: Generate and Push Caddyfile and Mermaid Diagram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install argparse

      - name: Generate Caddyfile
        run: |
          python reverse-proxy-config/.gen/gen.py reverse-proxy-config/domains.json reverse-proxy-config/Caddyfile

      - name: Generate Mermaid Diagram
        run: |
          python reverse-proxy-config/.gen/diag.py reverse-proxy-config/domains.json reverse-proxy-config/diagram.md

      - name: Embed Mermaid Diagram in README.md
        run: |
          mermaid_diagram=$(cat reverse-proxy-config/diagram.md)
          sed -i '/<!-- Mermaid Diagram Start -->/,/<!-- Mermaid Diagram End -->/c\<!-- Mermaid Diagram Start -->\n'"$mermaid_diagram"'\n<!-- Mermaid Diagram End -->' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reverse-proxy-config/Caddyfile README.md
          git commit -m 'Generate and update Caddyfile and Mermaid diagram'
          git push
